FROM ubuntu

RUN apt-get update \
    && apt-get install -y ansible 
RUN mkdir /java
WORKDIR /java
ADD ./group_processor /java/group_processor
ADD ./playbook.yml /java/playbook.yml
ADD ./roles /java/roles
ADD ./java.py /java/java.py
RUN chmod +x java.py
RUN /usr/bin/python java.py
RUN . /etc/profile
